export const PORT: number = Number(process.env.PORT) 
export const user = process.env.USER?.toString()
export const host = process.env.HOST?.toString()
export const password = process.env.PASSWORD?.toString()
export const db_port = Number(process.env.DB_PORT)
export const database = process.env.DATABASE?.toString()